config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "welcome#index"
  resources :products, only: [ :index, :new, :create ]
  resources :promotions, only: [ :index, :new, :create ]
  resources :carts, only: [ :new, :create, :show, :index ] do
    resources :cart_items, only: [ :create, :update, :destroy ]
    get :checkout, on: :member
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items

  def checkout!
    puts cart_items
  end

  def find_applicable_promotions
    products_in_cart = Product.where(id: cart_items.undiscounted.pluck(:product_id))
    applicable_promotions = Promotion.occurring_now.product_or_category_related(products: products_in_cart).uniq
    applicable_promotions.select do |promotion|
      promotion.promotionable.full_quantity_in_cart(cart_items: self.cart_items) >= promotion.minimum_quantity
    end || []
  end

  def add_product(product_id:, quantity:)
    item = cart_items.find_or_initialize_by(product_id:)
    previous_quantity = item.quantity || 0
    item.quantity = previous_quantity + quantity.to_i
    item.save!
  end

  def remove_product(product_id:)
    cart_items.find_by(product_id:).destroy
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def new
    @cart = Cart.create!
  end

  def checkout
    @cart = Cart.find(cart_params[:id])
    @cart_items = @cart.cart_items.ordered_by_category
    @checkout = ::Checkout.new(cart: @cart)
  end

  def show
    @cart = Cart.find(cart_params[:id])
    @cart_items = @cart.cart_items.ordered_by_category
    @applicable_promotions = @cart.find_applicable_promotions
  end

  def index
    @carts = Cart.all
  end

  private

  def cart_params
    params.permit(:id)
  end
end

app/views/carts/checkout.html.slim
title Checkout
.container.flex.flex-col
  turbo-frame id="cart_items"
    .container.flex.flex-col
      .container.rounded.mx-2.p-5.bg-white.flex.flex-col
        h1.font-bold Your Shopping Cart
        hr
        .container.mt-3.flex.flex-col
          table.border.table-auto.rounded-lg
            thead
              tr.bg-slate-400
                th.border Item
                th.border Brand
                th.border Quantity
                th.border Unit Price
                th.border Subtotal
                th.border Discount
                th.border Total
            tbody
              - @cart_items.each do |item|
                turbo-frame id="cart_item_#{item.id}"
                  tr
                    td.border = item.product.name
                    td.border = item.product.brand
                    td.border = item.human_units_of_sale
                    td.border = number_to_currency(item.product.cents_price_per_unit/100.00)
                    td.border = number_to_currency(item.quantity * item.product.cents_price_per_unit/100.00)
                    td.border = item.promotion&.code
                    td.border =  number_to_currency(@checkout.item_total(item:)/100.00)
          .container.mt-3
            h1.font-bold Total Price:
            hr
            h3 =  number_to_currency(@checkout.full_total / 100.00)

app/views/carts/index.html.slim
div.container.flex
  div.container.rounded.m-3.p-5.bg-white
    h1.font-bold Here's a list of all carts
    hr
    div.flex.flex-col
      -@carts.each do |cart|
        p = cart.attributes

app/views/carts/new.html.slim
title Cart
.container.flex.flex-col
  .container.rounded.mx-2.p-5.bg-white.flex.flex-col
    h1.font-bold Your Shopping Cart
    hr
    .container.mt-3.flex.flex-col
      h3.bold Cart is empty, please add product to cart.

  .container.rounded.mt-2.p-5.bg-white.flex.flex-col
    .container.flex-col
      h1.font-bold Add Product
      hr
      = form_with url: cart_cart_items_path(cart_id: @cart.id), method: :post, turbo: false do |f|
        = f.label :product_id, "Product", class: "mt-3 text-sm font-medium text-gray-700"
        = f.collection_select :id, Product.all, :id, :name,{allow_blank: false}, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
        = f.label :quantity, "Quantity", class: "mt-3 text-sm font-medium text-gray-700"
        = f.number_field :quantity, value: 1, min: 1, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
        = f.submit "Add to Cart", class: "mt-3 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 focus:outline-none dark:focus:ring-blue-800"

app/views/carts/show.html.slim
title Cart

.container.flex.flex-col
  turbo-frame id="cart_items"
    .container.flex.flex-col
      .container.rounded.mx-2.p-5.bg-white.flex.flex-col
        h1.font-bold Your Shopping Cart
        hr
        .container.mt-3.flex.flex-col
          -if @cart_items.empty?
            h3.bold Cart is empty, please add product to cart.
          -else
            table.border.table-auto.rounded-lg
              thead
                tr.bg-slate-400
                  th.border Item
                  th.border Brand
                  th.border Quantity
                  th.border Unit Price
                  th.border Subtotal
                  th.border Discount
                  th.border Actions
              tbody
                - @cart_items.each do |item|
                  turbo-frame id="cart_item_#{item.id}"
                    tr
                      td.border = item.product.name
                      td.border = item.product.brand
                      td.border = item.human_units_of_sale
                      td.border = number_to_currency(item.product.cents_price_per_unit/100.0)
                      td.border = number_to_currency(item.quantity * item.product.cents_price_per_unit/100.0)
                      td.border = item.promotion&.code
                      td.border = link_to "Remove", cart_cart_item_path(@cart.id, item.product.id), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?', turbo_frame: "cart_items" }, class: "text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-blue-300 font-sm rounded-lg px-5 py-1.5 text-sm focus:outline-none dark:focus:ring-blue-800"
            .container.mt-3
              = link_to "Checkout", checkout_cart_path(@cart), data: { turbo_frame: '_top' }, class: "text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 focus:outline-none"

      .container.rounded.mt-2.p-5.bg-white.flex.flex-col
        h1.font-bold Add Discount to Cart
        hr
          = form_with url: cart_cart_item_path(cart_id: @cart.id),method: :PATCH, data: { turbo_frame: "cart_items" } do |f|
            = f.label :discount_code, class: "mt-3 text-sm font-medium text-gray-700"
            = f.select :promotion_id, @applicable_promotions&.pluck(:code, :id), { allow_blank: false }, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
            = f.submit "Apply Promotion", class: "mt-3 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 focus:outline-none dark:focus:ring-blue-800"

  .container.rounded.mt-2.p-5.bg-white.flex.flex-col
    .container.flex-col
      h1.font-bold Add Product to Cart
      hr
      turbo-frame id="add_item_form"
        = form_with url: cart_cart_items_path(cart_id: @cart.id), method: :post, data: { turbo_frame: "cart_items" } do |f|
          = f.label :product_id, "Product", class: "mt-3 text-sm font-medium text-gray-700"
          = f.collection_select :id, Product.all, :id, :name,{allow_blank: false}, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
          = f.label :quantity, "Quantity", class: "mt-3 text-sm font-medium text-gray-700"
          = f.number_field :quantity, value: 1, min: 1, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
          = f.submit "Add to Cart", class: "mt-3 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 focus:outline-none dark:focus:ring-blue-800"